#!/bin/bash

getCommand()
{
    ps -p $1 -o command= | sed "s/^[^ ]*\///"
}

appendSortLines() # todo: clean up treatment of "external" parameter "sortLines"
{
    declare commandWindowPairs=`echo -e "$1" | sort`
    declare -i desktop=$2
    declare sortCommands
    declare command
    for pair in $commandWindowPairs
    do
	command=`echo "$pair" | cut -d : -f 1`
	if [ ! $sortCommands ] 
	then
	    sortCommands=$command
	else
	    sortCommands="$sortCommands --- $command"
	fi
    done
    for pair in $commandWindowPairs
    do
    	sortLines="$sortLines\n$sortCommands:$pair:$desktop"
    done
}

getWindows()
{
    IFS=$'\n' # so that the e.g. for loop below uses newline as separator
    declare sortLines=""
    declare -i lastDesktop=-1
    declare commandWindowPairs
    declare -i window
    declare -i desktop
    declare -i pid
    declare command
    for line in `wmctrl -lp`
    do 
	window=`echo "$line" | cut -d " " -f 1`
	desktop=`echo "$line" | cut -d " " -f 3`
        pid=`echo "$line" | cut -d " " -f 4`
        # title=`echo "$line" | cut -d " " -f 1,2,3,4,5,6 --complement` 
	command=`getCommand $pid`
	if [ $desktop -ne $lastDesktop ]
	then
	    if [ $lastDesktop -ne -1 ]
	    then
		appendSortLines "$commandWindowPairs" "$lastDesktop"
 	    fi
	    commandWindowPairs=$command:$window
	    lastDesktop=$desktop
	else
	    commandWindowPairs="$commandWindowPairs\n$command:$window"
	fi
    done
    appendSortLines "$commandWindowPairs" "$lastDesktop"
    sortLines=`echo -e "$sortLines" | sort`
    declare -i counter=1
    declare -i visibleDesktop=`wmctrl -d | grep \* | cut -d " " -f 1`
    declare gotoLines=""
    declare commands
    declare lastCommands
    for line in $sortLines 
    do 
	command=`echo "$line" | cut -d : -f 2`
	window=`echo "$line" | cut -d : -f 3`
	desktop=`echo "$line" | cut -d : -f 4`
	commands=`echo "$line" | cut -d : -f 1`
	if [ "$commands" != "$lastCommands" ]
	then
	    if [ -n "$gotoLines" ]
	    then
		gotoLines="$gotoLines\n"
	    fi
	    gotoLines="$gotoLines$counter goto $window "
 	    if [ $desktop -eq $visibleDesktop ] 
	    then
		gotoLines="$gotoLines*"
	    fi
	    gotoLines="$gotoLines$commands"
	    let counter=$counter+1    
	fi
	lastCommands=$commands
    done
    echo -e "$gotoLines"
#echo "-------------------------------------------------------------------------------------------------------------------------------------------------------------------------$bringLines"
#"$bringLines" on extra line causes trouble for some reason 
#echo "-------------------------------------------------------------------------------------------------------------------------------------------------------------------------"
}

main()
    {
	declare line=`(getWindows;dmenu_path) | dmenu -i -l 13` 
	declare -i window
	
	if echo "$line" | grep goto
	then
	    window=`echo "$line" | cut -d " " -f 3`
	    wmctrl -ia $window
	else
	    echo "$line" | grep bring
	    
	    if echo "$line" | grep bring 
	    then
		window=`echo "$line" | cut -d " " -f 3`
		wmctrl -iR $window
	    else
		exec $line
	    fi
	fi
    }

main
