#!/bin/sh
CACHE=${XDG_CACHE_HOME:-"$HOME/.cache"}/dmenu_run
(
	IFS=:
	if test "`ls -dt $PATH "$CACHE" 2> /dev/null | sed 1q`" != "$CACHE"; then
		mkdir -p "`dirname "$CACHE"`" && lsx-suckless $PATH | sort -u > "$CACHE"
	fi
)
cat $CACHE
